### ISSUE TITLE
Unable to clone

### ISSUE THREAD

**Issue by joshpetit** [Mantano/iridium#10]
Hey! So I'm trying to clone the source code to possibly contribute but receive this error when trying:

```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Mantano/mno_lcp_native' into submodule path '/home/joshu/projects/iridium/mno_lcp_native' failed
Failed to clone 'mno_lcp_native' a second time, aborting
```

I run the command found on the readme, some help would be appreciated! Thanks.

**Comment by joshpetit** [comment]
Also, I have to go into each directory and change the branch to develop (i use a sh script), but is there something with the submodules making it do that?

**Comment by jmgeffroy** [comment]
Hi Josh, sorry for the trouble and late reply (I didn't receive Github notifications for some reason). We have added mno_lcp_native by mistake: it is not currently needed. The simplest way for you to clone and get everything OK is by doing:
```
git clone --recurse-submodules https://github.com/Mantano/iridium.git
cd iridium
git checkout develop
cd app
flutter devices <-- Pick a device id in the list (in the 2nd column)
flutter run -d <device_id>
```
We have added these instructions to the README.
