### ISSUE TITLE
 【solved】flip many pages once a time

### ISSUE THREAD

**Issue by westernbuptboy** [Mantano/iridium#102]
Hello author, I have set “scroll-snap-stop=always” according to your issue, but in the end, the effect presented on iOS was to flip many pages, and after sliding stopped, it jumped back to the second page, without realizing that users can only flip one page at a time. Do you have a solution for this?

https://github.com/Mantano/iridium/assets/41902297/2629fc1b-d145-48da-acff-8249baa590a4

**Comment by westernbuptboy** [comment]
bug fixed，set decelerationRate:ScrollViewDecelerationRate.FAST to InAppWebView can solve this problem

**Comment by jmgeffroy** [comment]
Hi @westernbuptboy I'm very late, I know :-) Thanks for the fix! I have integrated it today.
