### ISSUE TITLE
Demo app fails to build with error: Member not found: 'STORE'.

### ISSUE THREAD

**Issue by sstennis1** [Mantano/iridium#103]
Per the instructions I tried to build the demo app for iOS using:

`> flutter run -d <some_simulator_device_ID>`

but it failed with the error:

`Error (Xcode): ../components/shared/lib/src/zip/lazy_zip_decoder.dart:26:60: Error: Member not found: 'STORE'.
`

I also tried building an iOS framework from the demo app using:

`> flutter build ios-framework --output=<some_path>`

and as expected it also failed with the same error:

```
../components/shared/lib/src/zip/lazy_zip_decoder.dart:26:60: Error: Member not found: 'STORE'.
   final compress = zf.compressionMethod != a.ZipFile.STORE;
```

I have the latest clone of the Iridium code and I'm using Flutter v3.16.2 with Dart v3.2.2 and DevTools 2.28.3. I'm very inexperienced with Flutter and Dart, so perhaps I'm doing something wrong.

**Comment by markusait** [comment]
Experiencing the same issue

**Comment by sstennis1** [comment]
Thanks for the tip @markusait!

**Comment by jmgeffroy** [comment]
Fixed! Thank you for pinpointing that.
