### ISSUE TITLE
How to console log to flutter debug console.

### ISSUE THREAD

**Issue by gwangbaekun** [Mantano/iridium#113]
Where can I see the console logs from flutter debug console or somewhere else?

```
  logError: function (message, filename, lineno) {
    console.error(message, filename, lineno);
  },
  log: function (message) {
    console.log(message);
  },
```

I tried with flutter.log("something");

not working on debug console.

What was the development environment when using this?

**Comment by jmgeffroy** [comment]
Hi @gwangbaekun, you can inspect the webview by opening in Chrome chrome://inspect. This page will show the webviews displayed in the app. You select one, and you'll see the DevTools. There, you'll see your JS logs in the Console tab.
