### ISSUE TITLE
Project is not running (build error)

### ISSUE THREAD

**Issue by umeshshende** [Mantano/iridium#114]
**Configuration** 
ext.kotlin_version = '1.8.20'
classpath 'com.android.tools.build:gradle:7.2.2'
API 34
Flutter 3.24.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 80c2e84975 (3 weeks ago) • 2024-07-30 23:06:49 +0700
Engine • revision b8800d88be
Tools • Dart 3.5.0 • DevTools 2.37.2

**Step Followed** 
i clone the repo 
go to demo app
flutter pub get
flutter run with device

**Getting below errors**
![1](https://github.com/user-attachments/assets/a77ebc19-6453-4d1e-af5b-f05dc4f2b63f)

**Comment by jmgeffroy** [comment]
Hi @umeshshende, thanks for the report. I finally have some (limited) time to do some cleanup and updates. I just pushed a commit that fixes it. I updated AGP and a lot of dependencies. Nothing really major, just maintenance for now.
Hopefully I'll have some more time in a few weeks when my current big project is released.
The demo app and reader widget demo app are working gain.

**Comment by umeshshende** [comment]
@jmgeffroy  When im loading epub its does nothing (by click add icon load epub). I want to load RTL epub for testing  so that i can implement same in another app 
![image](https://github.com/user-attachments/assets/9a8e8cc7-42e9-4684-b01a-fcc289df66c5)
