### ISSUE TITLE
Activate PageView scrolling only once page overlays are placed

### ISSUE THREAD

**Issue by jmgeffroy** [Mantano/iridium#19]

**Comment by vitaliynester** [comment]
Hello. I faced such problem. When scrolling pages quickly, the content in the WebView does not have time to fit and the scroll skips this page. Thus, with a quick scroll, you can scroll through the entire book. How to fix it? Where to look?

**Comment by vitaliynester** [comment]
I fixed this by calling the `epubController.pageController.animateToPage` method in the `onPageChanged` callback in navigator. And I added a handler that when I change the page I set the `PageView(physics: NeverScrollableScrollPhysics())`

**Comment by vitaliynester** [comment]
This fixed white screens on Android only. On iOS there is an error: `[ViewportSizing] maximumViewportInset cannot be larger than frame`. I keep looking
