### ISSUE TITLE
PreloadPageView poor performance with PlatformView

### ISSUE THREAD

**Issue by winterdl** [Mantano/iridium#2]
Congratulation for the implement Readium by Flutter. 

I have tried to implement in flutter but I was disappointed about performance of flutter webview and platformview could not be cache.

With the new navigator (the PreloadPageView will frozen the screen and only display blank white screen, i have to change it to PageView to run the demo), it runs okay on android but on ios device, the hoz gesture could not fired when reach the end of a chapter, I have to swipe from top right to bottom left if want go to next chapter or swipe from left bottom to top right if want go to prev chapter.  (I think ios PageView used BouncingScrollPhysics by default and android PageView use ClampingScrollPhysics)

The demo clip

https://user-images.githubusercontent.com/302480/147308696-376a4d60-c937-44a4-b5a7-dedc43f73110.MP4

And this is the native swift readium I have implemented for my client, it runs so smooth compare to flutter, but I prefer flutter than, waiting for flutter team improve the performance of platform view.

https://user-images.githubusercontent.com/302480/147308880-89567683-784a-400a-b198-e446eba5457e.MP4

**Comment by jmgeffroy** [comment]
Hi @winterdl!

Thanks a lot for your feedback. Glad to see you're still keeping an eye on the progress of this initiative ;-)

- About your Android issue ("PreloadPageView will frozen the screen and only display blank white screen"): this is a weird behaviour introduced recently, and is related to the Hybrid Composition mode. If you deactivate this mode (and hence switch to Virtual Display), the bug disappears but when swiping pages you can miss a few frames: it's less smooth.
You can try to get the latest "monorepo" that I have just uploaded this morning (checkout feature/monorepo), it does use Virtual Display mode (line 63 is commented out: 
```
    // if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
```
- iOS issue: We'll have a look shortly at it, this is probably easy to fix: in fact, this new navigator is extracted/adapted from our own app (still unreleased), where we don't have this behavior. It's very very smooth. However please wait until the beginning of January since part of the team is on holiday for now. 

Cheers

**Comment by jmgeffroy** [comment]
Update @winterdl I have tested in our own app (Mantano, which is the cradle of Iridium), and we also have the iOS issue now.  It's a recent regression. I'll track and fix it asap. It used to work smoothly.

**Comment by jmgeffroy** [comment]
Hi @winterdl , I have a quick n' dirty fix: you can simply add `viewportFraction: 0.999` in [`epub_controller.dart`](https://github.com/Mantano/iridium/blob/feature/monorepo/modules/mno_navigator_flutter/lib/src/epub/epub_controller.dart):
```
  @override
  void initPageController(int initialPage) =>
      _pageController = PreloadPageController(
          keepPage: true, initialPage: initialPage, viewportFraction: 0.999);
```
It's only a workaround but it works (a few quirks remain).

**Comment by winterdl** [comment]
Thank you for the update, I've faced the same issue about overscroll even of webview on ios, I have to set the viewport size as you too.
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1005

**Comment by jmgeffroy** [comment]
Thank you for sharing your previous experience. I'm sure there is a better solution because it worked without this trick, however. It prevents preloading multiple spine items, which can provide poor UX. BTW it also makes the PreloadPageView pointless.
I'll keep investigating.

**Comment by winterdl** [comment]
I dont think use preloadpageview is the way to go, but we need webview could  be able created and load webpage without attached to widget tree. With android native webview, we could create webview and preload webpage in memory without render.

**Comment by jmgeffroy** [comment]
Hi @winterdl For some reason I didn't receive Github notifications. I hope it's fixed now. With webview_flutter, we can also preload webpages without rendering (it relies on Android's WebView and iOS WkWebView as you probably know). But it does work when using Virtual Displays (which was the default on webview_flutter < 3.0.0), and does NOT work when using Hybrid Composition. I am currently having a discussion with a guy who seems in charge of webview_flutter, but I must provide him with a canonical example project, which I didn't find time to make. More precisely I provided a first one but it was not clean enough. 
The [discussion is here](https://github.com/flutter/flutter/issues/95938), but I think I'll start a new one from scratch to clean up the noise. The title mentions iOS, but it occurs on Android too, when using Hybrid Composition (which is the only option on iOS).
This is very high on my TODO list.

Besides that, about PreloadPageView: it simply allows having N webviews created in advance (PageView doesn't allow that). But without having proper preload, I agree it is irrelevant...
