### ISSUE TITLE
clicking in contents tab does not go to chapter in reader_widget and widget_demo 

### ISSUE THREAD

**Issue by jaded0** [Mantano/iridium#47]
Using reader_widget and widget_demo, clicking on a chapter in the table of contents does nothing except close the table of contents.

**Comment by jaded0** [comment]
It's possible that the issue is due to the use of a nav.xhtml instead of toc.ncx, since the michelin guide test epub does seem to be working.

**Comment by jmgeffroy** [comment]
Hi @jaded0 can you please tell me which book exhibits this issue?

**Comment by jaded0** [comment]
Sure! That's in my test epubs, but the problem also occurs in your accessible_epub_3.epub

**Comment by jaded0** [comment]
Seems like PublicationController is being given a GoToHrefCommand that has a spineItemIndex of -1.

**Comment by jaded0** [comment]
ope! fixed it. It was a line in reader_command_processor.dart :
```dart
publication.pageLinks.indexWhere(
            (spineItem) => spineItem.href.removePrefix("/") == command.href);
```
`command.href`, in the case of my test epubs, still had the prefix, and thus `indexWhere` found no index that matched.   
Removing `.removePrefix("/")` fixes it for my own app, but so does changing the href anywhere in the chain that led there, from `content_panel.dart`'s _onTap, to reader_commands.dart, to reader_command_processor.dart:
proposed fix:
```dart
@override
  int findSpineItemIndex(GoToHrefCommand command, Publication publication) => publication.pageLinks.indexWhere(
            (spineItem) => spineItem.href.removePrefix("/") == command.href.removePrefix("/"));
```
I'll test this with a variety of epubs and push the fix to your dev and main branches, so you can choose. Which do you prefer, between adding it to dev or to main?

**Comment by jmgeffroy** [comment]
Hi, @jaded0! Thanks a lot for your fix! Looks good to me. Yes, for your future PRs, please do them against our develop branch. I see that you have done a PR for main, this is OK, I'll merge and integrate that also in `develop`.
Cheers
