### ISSUE TITLE
Android: jquery security vulnerability prevents test success and app store uploads

### ISSUE THREAD

**Issue by jaded0** [Mantano/iridium#57]
The vulnerability, and error code, in mention:
```
    JavaScript jquery 2.1.0 SNYK-npm:jquery:20150627, SNYK-JS-JQUERY-174006 assets/flutter_assets/packages/mno_navigator/assets/xpub-shared-js/jquery-2.1.0.min.js
```

**Comment by jaded0** [comment]
It appear that this issue may be resolved in the enhancements/nojquery branch. @jmgeffroy  may I ask whether that might work out? How were you able to publish the demo app to the play store?

**Comment by jaded0** [comment]
Sorry, I had ended up just commenting out the header. My specific use-case didn't make the vulnerability serious. 
Sounds good, and thanks for the update!

**Comment by jmgeffroy** [comment]
Greta, thank you for this feedback!
