### ISSUE TITLE
Toggle mark disappears when a user exits the Reader Screen

### ISSUE THREAD

**Issue by mohngina** [Mantano/iridium#58]
When a user presses on the bookmark and the togglemark appears on the particular page, I noticed that when one
exits the reader screen and then comes back, the togglemark is usually already disappeared.

**Comment by jmgeffroy** [comment]
Each integration must implement its own storage strategy for the annotations, by implementing `[ReaderAnnotationRepository](https://github.com/Mantano/iridium/blob/main/components/navigator/lib/src/publication/model/reader_annotation_repository.dart)`. The SDK itself provides an `[InMemoryReaderAnnotationRepository](https://github.com/Mantano/iridium/blob/main/demo-app/lib/views/viewers/model/in_memory_reader_annotation_repository.dart)` but each app can choose its own type of storage (SQL, Firebase, ...).
So this is not an issue, but we should indicate that in the documentation.
