### ISSUE TITLE
inconsistent location

### ISSUE THREAD

**Issue by charlestyra89** [Mantano/iridium#81]
greetings,

working on an app that utilizes the epub reader. I noticed that the location seems to behave a little inconsistently. It will save the location at 45% when closing the book and then open the ebook again at 36% or some random percent location, sometimes 0%. So far with testing, I have never been able to make it reopen the epub to the exact page I left off on. Thanks for any help you can provide!

**Comment by eriquezinedine** [comment]
Hello, did you find a solution to this problem?

**Comment by charlestyra89** [comment]
> Hello, did you find a solution to this problem?

Not really, I did find that the epub being properly organized helped. Like, if the epub file is one giant html file, the reader doesn't handle that well compared to each chapter/section being in its own html file within the epub.
