### ISSUE TITLE
[IOS] Page turning not working

### ISSUE THREAD

**Issue by vitaliynester** [Mantano/iridium#85]
Hello @jmgeffroy I've noticed that page turning doesn't work on iOS devices. On Android, everything is fine, the problem occurs on iOS. Can you help somehow? Attached is a video of how it works.

https://github.com/Mantano/iridium/assets/36518409/9c15ba7b-40c3-4a48-bfe3-2d93dc0f4a36

**Comment by vitaliynester** [comment]
Everything works fine if you set viewportFraction: 1

**Comment by jmgeffroy** [comment]
Hi @vitaliynester, thank you for these comments. We used viewportFraction < 1 to force *prerendering* (not just preloading) the next spine item, but this may be unnecessary now. We did a lot of investigation about it a few years ago when starting this project, and I need to check it again. Anyway, you'll be fine with viewportFraction = 1. The only potential issie is that you might encounter some small delays when arriving on a new spine item (typically, a chapter).
