### ISSUE TITLE
Can't delete ebooks

### ISSUE THREAD

**Issue by charlestyra89** [Mantano/iridium#97]
Hello,

I am seeing an issue with a fresh pull of the code, where an error happens when you dismiss to delete a downloaded ebook. Plus the book doesn't delete and is there when you leave and return to the downloads screen.

`The following _TypeError was thrown while notifying listeners for AnimationController:
type 'String' is not a subtype of type 'Map<dynamic, dynamic>'

When the exception was thrown, this was the stack: 
#0      _DownloadsState._deleteBook (package:iridium_app/views/downloads/downloads.dart:205:17)`

**Comment by charlestyra89** [comment]
Found the issue. It isn't a problem with the reader. It is in the demo app. 
The id is being sent to the database helper when it is expecting the entire object.
In the following method in downloads.dart

the call should be changed to db.remove(dl).then...

  void _deleteBook(Map dl, int index) {
    db.remove(dl['id']).then((v) async { 
      File f = File(dl['path']);
      if (await f.exists()) {
        f.delete();
      }
      setState(() {
        dls.removeAt(index);
      });
    });
  }

**Comment by jmgeffroy** [comment]
Hi @charlestyra89! Thanks a lot for your fix. I just pushed [your fix](https://github.com/Mantano/iridium/commit/d11e52639c67b066c80f2808f3b0a83aa5194395) a few seconds ago.
